### ISSUE TITLE
Is it using Tensorflow?

### ISSUE THREAD

**Issue by Steviey** [dhrushilbadani/deeplearning-timeseries#2]
Is it using Tensorflow?
And which Python version is used?

**Comment by Zouxiaowu** [comment]
Tensorflow and Theano both okay I think, and I tested by Tensorflow.

**Comment by Zouxiaowu** [comment]
Tensorflow and Theano both okay I think, and I tested by Tensorflow.

**Comment by dhrushilbadani** [comment]
Both should be okay; I used Theano.
